### ISSUE TITLE
Unexpected repr of sliced list with [:]

### ISSUE THREAD

**Issue by pya** [billpmurphy/hask#9]
The representation of a sliced list with an end index looks as expected: 

```
>>> L[1, 2, 3][:10]
L[1, 2, 3]
```

Using the `[:]` to "slice" the whole list shows extra `...`:

```
L[1, 2, 3][:]
L[1, 2, 3 ...]
```

Is this intentional? If yes, what is the rational behind it?

**Comment by billpmurphy** [comment]
Nice find! This is indeed a bug; when you use `[:]`, Hask "forgets" that the `List` is fully evaluated, and so it prints the `...` to represent potentially unevaluated elements at the tail of the list.
